services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: brfn_postgres
      POSTGRES_PASSWORD: db_123
      POSTGRES_DB: brfn_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db: