# Generated by Django 6.0.3 on 2026-03-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits_from', to='order_management.orderstatus')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='order_management.order')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_to', to='order_management.orderstatus')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_orders', to='account_management.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to='order_management.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBusinessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producer_audits_from', to='order_management.orderstatus')),
                ('producer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='order_management.orderbusiness')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_audits_to', to='order_management.orderstatus')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderbusiness',
            constraint=models.UniqueConstraint(fields=('order', 'business'), name='uq_order_business'),
        ),
    ]
